### ISSUE TITLE
Erros de build apos inclusão do LINT_CHECK no travis.yml

### ISSUE THREAD

**Issue by mstuttgart** [odoo-brazil/odoo-brazil-addons#10]
O repo está com alguns erros de build e PEP8. 
https://travis-ci.org/odoo-brazil/odoo-brazil-addons/jobs/91805746

**Comment by mstuttgart** [comment]
@danimaribeiro a inclusão do LINT_CHECK="1" trouxe alguns erros de build. Consertei a maioria deles, mas ele ainda está acusando o erro abaixo:

![build](https://cloud.githubusercontent.com/assets/8174740/11338371/d0a901fe-91da-11e5-8c70-cbc4c449b7c8.png)

Sabe como faço passa resolver os warnings? Se usar a sugestão provida pelo LINT, não consigo inciiar o Odoo por erro _import_

**Comment by danimaribeiro** [comment]
Estranho isto, todos os imports são iguais da OCA.
Tenta criar um PR do teu branch para cá, talvez esteja usando uma versão errada. O PR vai dar um trigger em um novo build.

Em último caso talvez mudar os imports para "from openerp.addons.l10n_br_zip...."

**Comment by rvalyi** [comment]
@mstuttgart legal botar o coverage aqui. Alias, eu tinha falado atingir 50% para botar na OCA. Seria legal atingir 70%. Acho que no caso a partir do momento que vc vai fazer um mock sera facil. O lance e que seria legal falar que a localizacao na OCA tem que ficar acima de 70%. Ai e bom nehnum modulo vir atrapalhar essa meta; tamos quasi la. E importante antes de migrar ou para aceitar contribuicoes etc...

**Comment by mstuttgart** [comment]
@danimaribeiro eu já havia tentado tentei mudar os _imports_ para a sugestão que você falou "from openerp.addons.l10n_br_zip". Aparentemente funciona, mas eu não deixei assim porque olhando os repositorios da OCA, percebi que nenhum deles a usava. 
De qualquer maneira, vou fazer o PR pra testar. :+1: 

@rvalyi estou de olho nisso. Já trabalhei em alguns testes para os módulos do Odoo Brazil. Assim que chegar em 70% com todos os testes, eu te aviso. :+1:
